name: nutrisnap
description: A health tracking app like HealthifyMe – AI + SQLite + Offline.

publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path: ^1.8.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/sample_meal.jpg
